apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: rss-feeder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: 'postgres:16'
          args:
            - "-c"
            - "password_encryption=scram-sha-256"
            - "-c"
            - "listen_addresses=*"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: rss-feeder-secrets
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresdata
      volumes:
        - name: postgresdata
          persistentVolumeClaim:
            claimName: postgres-volume-claim

