apiVersion: apps/v1
kind: Deployment
metadata:
  name: rss-feeder
  namespace: rss-feeder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rss-feeder
  template:
    metadata:
      labels:
        app: rss-feeder
    spec:
      containers:
        - name: rss-feeder
          image: 'dylanwe/rss-feeder:latest'
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: rss-feeder-secrets

