apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rss-feeder-claim
  labels:
    app: rss-feeder
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
