apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  namespace: rss-feeder
  labels:
    type: local
    app: rss-feeder
spec:
  storageClassName: local-path
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/postgresql

