apiVersion: v1
kind: Service
metadata:
  name: rss-feeder
  labels:
    app: rss-feeder
spec:
  type: NodePort
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
  selector:
    app: rss-feeder-postgres
